### ISSUE TITLE
Question: is this replacement for VNXTLP?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/SacanaWrapper#1]
is this replacement? and whats the differences?

**Comment by marcussacana** [comment]
VNXTLP i use to my projects, have a GUI, string filter, Automatic Backup, spell check and more...
The StringTool is just a .txt dump/import

The reason of this SacanaWrapper is to i use with my VNTXLP to don't need fuck the source with #if or need rebuild to change the engine... this is to i use my tools as plugin to my VNTXLP
This StringTool is just a bonus.

**Comment by marcussacana** [comment]
soo... i don't think is a replacement but a new feature

**Comment by 0xh3LL0** [comment]
ok, thanks for the explanation...
