### ISSUE TITLE
Help with plugins 

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/SacanaWrapper#11]
Hi, Fisch again.
I downloaded SacanaWrapper as you asked and made a plugin directory trough visual studio.
I tried to start up PMan.exe but I can't start it because some error.
I thought that I must have some plugins.
![error](https://user-images.githubusercontent.com/69847532/94198445-8f9b2080-feb7-11ea-9b7a-c0c454801ff1.PNG)

But when I look to that directory there weren't any plugins.
What am I doing wrong?
Should I download your own plugins or I can just drop files from MWare stuff- master?
Can you help me? Thanks.
![dll2](https://user-images.githubusercontent.com/69847532/94169001-88135180-fe8e-11ea-9353-56eefa7ab1be.PNG)
![dll3](https://user-images.githubusercontent.com/69847532/94169003-88135180-fe8e-11ea-97ce-197bc6b09ed7.PNG)

**Comment by marcussacana** [comment]
See the details message

**Comment by fisch123456** [comment]
It says that it must have debbuging value set to True
and I am afraid to change something in windows. Hope you understand and forgive me if I am bothering you.
Thanks.
![eror2](https://user-images.githubusercontent.com/69847532/94309795-eb79ae00-ff78-11ea-8b95-9b7886ed76e7.PNG)

**Comment by fisch123456** [comment]
It says that I must set system. windows. form section to true but I am afraid to change something in Windows 
Is it really necessary?
Sorry if I am bothering you. 
Thanks
![eror2](https://user-images.githubusercontent.com/69847532/94310610-30eaab00-ff7a-11ea-86a8-6641e2ad8d8b.PNG)

**Comment by fisch123456** [comment]
I aw it and it says that I have to set value in system.windows.forms to true.
But I am afraid to change something in windows.
Is it really necessary?
Hope you understand and I am sorry if I bothering you.
Thanks.
![eror2](https://user-images.githubusercontent.com/69847532/94311604-d6524e80-ff7b-11ea-8697-946cfa64679c.PNG)

**Comment by marcussacana** [comment]
Missing Information, but probably you did something wrong.

**Comment by marcussacana** [comment]
Install .net core 2.1, .net core 3.1 and all .net framework, then try again, if the error persist reinstall your windows, i'm not with time to analyze what happen to you

**Comment by fisch123456** [comment]
ok I understand.

**Comment by fisch123456** [comment]
I found a mistake in your program when debugging.
![kod](https://user-images.githubusercontent.com/69847532/94322602-3e605f00-ff93-11ea-9e10-d8f2c1b6f605.PNG)
Should it be there?
I don't want to dehonest your work just asking because that can be the problem.

**Comment by fisch123456** [comment]
Hi, When I tried to debugging again a come up with the error.I saw the error sooner but I ignore it because release and debug file appeared.Should it be there? I don't want to dehonest your work just to be sure that this is not the problem. Thanks
![kod](https://user-images.githubusercontent.com/69847532/94323280-6e106680-ff95-11ea-855e-a3c3e4c56e11.PNG)

**Comment by marcussacana** [comment]
This have a auto-update, he should verify the version in this part,
maybe in your build the sacanawrapper don't have any information about the version then the version check crashes.

**Comment by fisch123456** [comment]
Do you know how to fix that?

**Comment by marcussacana** [comment]
remove that part of the code and anything that miss that part

**Comment by fisch123456** [comment]
Hi, so I set value to True but I got a new error which says that I got mistake in the machine configuration.
I set it back and I got the same error as before. Do you know where is the problem?
Can you help me please? Thank you.
![eror4](https://user-images.githubusercontent.com/69847532/94345855-26d3b580-0029-11eb-931c-3fd4f5016e87.PNG)
