### ISSUE TITLE
Error in debugging Pman

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/SacanaWrapper#13]
Hi, sorry that I am opening another issue but I have trouble with checking on new updates line.
I know that we spoke about that earlier but I would like to know if it is possible to fix it somehow.
When I tried to erase lines similiar with it the program just couldn't work.
And I think I wouldn't be able to fix that program ever.
I have newest build but that still doesn't work.
I got newest net framework, net 3 and net 2 installed.
Will you help me? If not I will understand.

**Comment by marcussacana** [comment]
Remove this 
https://github.com/marcussacana/SacanaWrapper/blob/4573e062142e16b82037ac0714493fa570715c2a/PMan/Update.cs#L19-L31

**Comment by fisch123456** [comment]
Thanks you you are the best
