### ISSUE TITLE
Help with instructions.

### ISSUE THREAD

**Issue by fisch123456** [marcussacana/SacanaWrapper#14]
Hi Fisch here. Thanks for recent comments I really appreciate it. Now i got everyhing - guess.
Pman - Mware nute editor.dll and mware editor.ini.
I also have files in sacanawrapper file
mware tool is also compiled and I have all the files.
What I am trying to say is that I don§t know what should do next.I want open nut files but I don't know how to create it.
What should have go where.
I need better instuctions.
Can you help me please?
Thanks.

**Comment by marcussacana** [comment]
... You're trying use my tools or debug/modify?
If is just use your entire work has a lost of time, because I have ready-to-use builds of the sacanawrapper with stringtool

**Comment by fisch123456** [comment]
I want to open totono nut files with your tools. 
Fisrtly I opened npk with your mware engine.
Then I asked you how to open nut files
I downloaded your sacanawraper tool.
I created it with visual studio.
Now I got all the files and I am asking for help what to do next.

**Comment by marcussacana** [comment]
1 - Download the Plugin Manager and SacanaWrapper 
3 - Extract both to the same directory
4 - Open the PMan.exe
5 - Search for NUT, and install the NUTEditor plugin
6 - Drag&Drop your NUT files to the stringtool.exe

**Comment by fisch123456** [comment]
Hi, thanks for the great instruction it was very helpfull, but after I drop capp.nut file into the stringtool it only gives me empty text file. Is it possible that it doesn't work on totono from steam? Thanks for answer.

**Comment by marcussacana** [comment]
The NUTEditor only allow edit the text, also have 2 versions try install the other one if you found problems

**Comment by fisch123456** [comment]
Hi I know that you actually closed this issue but I would like to ask. 
After infinity attempts I managed to find a mistake - forgot to debug stringtool.
And got something like this.
Is is how to supposed to look like because I think people can make changes in game.
![subor](https://user-images.githubusercontent.com/69847532/94752391-61bc4d00-038b-11eb-95a6-e40e5d5ed4fc.PNG)
Thanks for answer and if it's possible can I write you on your mail?
I don't want to open another issues.

**Comment by marcussacana** [comment]
feel free to, but usually I don't read my emails

**Comment by fisch123456** [comment]
Hi I just wanted to thank for everything that you done to me.For your patience and quick response. And thanks you for this tools that can open this game.Now I can finally translate this game to my own language despite a very low amount of people are reading visual novels.I checked VNX site and I will consider to join to your comunity if it is possible to translate it to the other languages except brazil.Also I was wondering if you have any experience with npf files which i found in the nitroplus directory which stores game data.I would like to ask you if it is possible to open them.Thanks for answer and wish good luck. Fisch.

**Comment by marcussacana** [comment]
Nop, the VNX is limited to the brazil to direct support, but indirect support we help as well, anyway, no idea about the npf
