### ISSUE TITLE
Ignore names (Krkr filter)

### ISSUE THREAD

**Issue by Cerzs** [marcussacana/SacanaWrapper#15]
Hi! I would like to know how can I ignore names in the TXT result. I think this is a KrKrFilter.cs feature. My Sacana used to omit names, but no longer does.

Example:

> Narration
> "Iris-chan's in a very good mood."
> Narration
> "Why won't Japan shoot when they're wide open?"
> Iris
> "Iris-chan suddenly starts talking soccer."
> Narration

TO

> "Iris-chan's in a very good mood."
> "Why won't Japan shoot when they're wide open?"
> "Iris-chan suddenly starts talking soccer."

[Here's a sample](https://cdn.discordapp.com/attachments/754950553590825032/831756713019047966/B11_end_en.ks).

**Comment by marcussacana** [comment]
remove the attribute entries in this line:
https://github.com/marcussacana/SacanaWrapper/blob/7687db2fbccab54a088f411daa5bf6b8bc53be9e/Updater/KrKrFilter.cs#L134
I think the chara is used in this game.

**Comment by Cerzs** [comment]
Thank you!
