### ISSUE TITLE
Question: Can you add support for PJADV?

### ISSUE THREAD

**Issue by Cosetto** [marcussacana/SacanaWrapper#16]
The engine itself doesn't need repack you just put the textdata.bin into directory but here the problem
This is the one I used GARbro to extract 
![image](https://user-images.githubusercontent.com/81801486/135398238-11bbc9aa-7a4c-44c6-a420-0bab3a1aaf01.png)
![image](https://user-images.githubusercontent.com/81801486/135398259-81333691-4d8e-44cd-b3f3-eb9c35f357a1.png)
And this is the one I used AE VN tool
![image](https://user-images.githubusercontent.com/81801486/135398446-5b17efed-6a9b-4c96-9589-3c099883c9f9.png)
![image](https://user-images.githubusercontent.com/81801486/135398500-3b1510a6-2f9c-4b3f-b87b-3873b842337c.png)
This is the script of the game I am trying https://vndb.org/v19612
[textdata.zip](https://github.com/marcussacana/SacanaWrapper/files/7257161/textdata.zip)

**Comment by marcussacana** [comment]
Well, I can give a try but my i'm with lack of time currently

**Comment by marcussacana** [comment]
The reason of the garbro seems better to extract and don't works, probabbly because the script is encrypted or compressed, and the garbro extract/decrypt the script content, while the engine only support the encrypted/compressed script, basically we need keep the file encrypted/compressed just like the AE Tools did

**Comment by Cosetto** [comment]
So I found a python code to decrypt the textdata.bin and codes for extract/insert but when I try to encrypt it this happened. I actually reversed the decrypt.py 
![image](https://user-images.githubusercontent.com/81801486/136655853-be5ddc3e-1335-4cc1-a44c-f9ce2d6cf60c.png)
[PJADV.zip](https://github.com/marcussacana/SacanaWrapper/files/7315478/PJADV.zip)
