### ISSUE TITLE
Nora to Oujo to Noraneko Heart data.xp3

### ISSUE THREAD

**Issue by leminhyen2** [marcussacana/SacanaWrapper#18]
Hi Marcus, I noticed that you are part of the restoration team for this game. 

I wanted to translate this game to my language and so, use english script as the base.

However, when I tried to open the data.xp3 file with other tools like Crass, arc_unpacker, GARbro, nothing worked

Do you happen to have the tool for that open sourced anywhere or if possible share it with me?

Thank you for making all these wonderful tools

**Comment by marcussacana** [comment]
https://github.com/xmoeproject/KrkrExtract/
