### ISSUE TITLE
can i change encoding

### ISSUE THREAD

**Issue by xd2333** [marcussacana/SacanaWrapper#19]
i wana insert txt with encoding 936, is there any way to do this, or the only way is rebuild plug dll? thanks.

**Comment by marcussacana** [comment]
The TXT encoding is UTF8 and is unrelated with the script encoding, usually change the script encoding will just break things and don't will works as you maybe expect (put non japanese characters in the game), anyway you will need modify the dll and change the default encoding to the one that you need.

**Comment by xd2333** [comment]
got it
