### ISSUE TITLE
can i import txt which include simplified Chinese

### ISSUE THREAD

**Issue by onecatcute** [marcussacana/SacanaWrapper#21]
i got the way to make game text show chinese.
after i import txt which innclude simplified Chinese，some words show normal，and some words  turn to '?'
can i modify the code to make all words show normal?

**Comment by marcussacana** [comment]
This will require change the engine encoding, you can see how some engines you can translate for chinese and some others not.
The SCN from Kirikiri is a format that support chinese for example.
And the CST from CatSystem is a format that don't support chinese.
That's because the game text is in the SJIS encoding, you will need patch the game engine or maybe modify the font and remap the unused japanese characters with your chinese ones.

**Comment by onecatcute** [comment]
I'm sorry to make you misunderstood me.
i have changed the engine encoding and exactly read the game text.bin which include simplified Chinese.
i put game text.bin into StringTool.exe and export the game text.txt. it is normal.
but after i edit the game text.txt which include simplified Chinese，it is going to put game text.txt into StringTool.exe for import txt.  i do it and get text.bin_new. i export text.bin_new to txt and find some words turn to '?'
can i modify the code to import Correctly txt which include simplified Chinese into text.bin

**Comment by Cosetto** [comment]
> I'm sorry to make you misunderstood me. i have changed the engine encoding and exactly read the game text.bin which include simplified Chinese. i put game text.bin into StringTool.exe and export the game text.txt. it is normal. but after i edit the game text.txt which include simplified Chinese，it is going to put game text.txt into StringTool.exe for import txt. i do it and get text.bin_new. i export text.bin_new to txt and find some words turn to '?' can i modify the code to import Correctly txt which include simplified Chinese into text.bin

It is because sacanawrapper inserts shift-jis(cp932), you need to modify the encoding to gbk(cp936) to insert Chinese letters correctly

**Comment by marcussacana** [comment]
As said, if you have already a modded engine to read the chinese encoding, you just need find the plugin repo that you're using and modify the encoding to the chinese one.

**Comment by onecatcute** [comment]
where and how to moify ？Is it to modify the source code? or is it to modify the file.dll under Plugins folder?

**Comment by onecatcute** [comment]
i can't find the place to set the code.

**Comment by onecatcute** [comment]
I can't find the place to set the encode.

**Comment by marcussacana** [comment]
what is the plugin that you're using?

**Comment by onecatcute** [comment]
Escude engine script editor

**Comment by marcussacana** [comment]
https://github.com/marcussacana/EscudeEditor/blob/master/EscudeEditor/BinScript.cs#L14
But you may need take a attention to the obfuscation of the string.

**Comment by onecatcute** [comment]
what is 'obfuscation of the string'? What will happen to it?

**Comment by onecatcute** [comment]
i got it.  thanks a lot.

**Comment by pxBang** [comment]
> i got it. thanks a lot.我得到了它。多谢。

由于不知道您的联系方式，只能在这里和您联系！

非常感谢您提的ISSUE，这帮助我解决了问题：将utf-8编码格式的脚本注入了.bin文件！

然而经过长时间的调试，我现在遇到了第二个问题：如何让Escude引擎的游戏正确显示utf-8编码格式的脚本？

这困扰了我许久，这几天在不断测试，耗费了我很长时间，很幸运在这里能遇到中国人（我猜测您是中国人？），而且遇到了同样的问题，可能您的一句回答，将帮助我解决问题！

最后再次感谢您的ISSUE,以及感谢该仓库的作者！

期待您的回复！

**Comment by marcussacana** [comment]
> > i got it. thanks a lot.我得到了它。多谢。
> 
> 由于不知道您的联系方式，只能在这里和您联系！
> 
> 非常感谢您提的ISSUE，这帮助我解决了问题：将utf-8编码格式的脚本注入了.bin文件！
> 
> 然而经过长时间的调试，我现在遇到了第二个问题：如何让Escude引擎的游戏正确显示utf-8编码格式的脚本？
> 
> 这困扰了我许久，这几天在不断测试，耗费了我很长时间，很幸运在这里能遇到中国人（我猜测您是中国人？），而且遇到了同样的问题，可能您的一句回答，将帮助我解决问题！
> 
> 最后再次感谢您的ISSUE,以及感谢该仓库的作者！
> 
> 期待您的回复！

Usually the process is to hook or patch the calls to `MultiByteToWideChar/WideCharToMultiByte` and modify the codepage param with your chinese one, some calls to method that finish with `A` in the name, like `CreateFontA/CreateFontIndirectA` will need paching as well

**Comment by onecatcute** [comment]
> > i got it. thanks a lot.我得到了它。多谢。
> 
> 由于不知道您的联系方式，只能在这里和您联系！
> 
> 非常感谢您提的ISSUE，这帮助我解决了问题：将utf-8编码格式的脚本注入了.bin文件！
> 
> 然而经过长时间的调试，我现在遇到了第二个问题：如何让Escude引擎的游戏正确显示utf-8编码格式的脚本？
> 
> 这困扰了我许久，这几天在不断测试，耗费了我很长时间，很幸运在这里能遇到中国人（我猜测您是中国人？），而且遇到了同样的问题，可能您的一句回答，将帮助我解决问题！
> 
> 最后再次感谢您的ISSUE,以及感谢该仓库的作者！
> 
> 期待您的回复！

我所为之如作者所言，这是正确的做法。将GBK编码格式的文本注入了.bin文件，再使用x32dgb打开exe文件，找到CreateFontIndirectA所指向的读取文本设置的编码80改成86，最后在lib目录下string.h里的“#define ISKANJII(x) ......"这句字符检测，改成”#define ISKANJII(x) ((x)>=0x81)"。就好了。
