### ISSUE TITLE
Issue with dumping scripts from PlayStation Vita version of Rewrite

### ISSUE THREAD

**Issue by badspott** [marcussacana/SacanaWrapper#25]
Hello and thank you for making this awesome tool.
I'm currently (in progress) working on an English patch for PS Vita version of Key's visual novel Rewrite.
I've noticed that Prototype Plugin doesn't full dump some parts of the script.
Here are some of files as an example (dumped txt and .psb file).
[022_8597829.dump.txt](https://github.com/marcussacana/SacanaWrapper/files/11985162/022_8597829.dump.txt)
.psb file: https://files.catbox.moe/zroa2u.psb
Apologies for uploading it to catbox as GitHub doesn't allow me to upload .psb files.
Parts of the script that are missing are this dump (from the PC version of Rewrite's seen01003)
```
[瑚太朗] 「…一仕事だったな」
[瑚太朗] 「引きあげるか」
[瑚太朗] 「………ん？」
背後から視線を感じたような気がした。
[瑚太朗] 「…まさか」
猫とか犬とか、そんなのだろうか。
[瑚太朗] 「帰るか…」
歩き出した途端、後ろから何かが押し寄せ、背中を包んだ。
薄絹の束のようなもの。
大量に。
[瑚太朗] 「…え？」
振り返る。
何もない。
誰もいない。
ただ、その先には森があるだけだ。
首筋に絡んだ感触はまだ克明だというのに。
さらりとした…なのにイヤな感じだ。
…深い森。
数秒遅れて、腕に鳥肌が立った。
[瑚太朗] 「………っ」
逃げるように家路を急いだ。
小鳥は森を庭みたいなものと言う。
けど今の俺には、とてもそんな安らぐ場所とは思えなかった。
深夜。
俺は眠りに落ちつつあった。
[瑚太朗] 「………………」
[瑚太朗] 「ひぃぃぃぃぃぃぃぃっ！」
突然、誰かに手首を握られ恐怖に駆られた。
氷のように冷たい手だった。
[瑚太朗] 「だ、だれっ？　何奴！」
ベッドから転がり出て、電気をつけた。
誰もいない。
[瑚太朗] （…気のせいか？）
感触はまだ手首にひんやりと残っている。
かなり強い力で握られ、腕を引かれたはずだ。
半分眠りかけていた俺がぎょっとして目覚めるくらい、強い力だった。
まるで腕を引っこ抜こうとするかのような…
[瑚太朗] 「なんだこりゃ…？」
照明の下、手首を見る。
強い力で握られた証が、くっきりと浮かんでいた。
つまり手形が。
[瑚太朗] 「………………」
俺はさっくりと気絶した。
…これ、夢だよな…。
```
I've looked into the .psb file via hex editing and the missing parts of the script are there. It's just that StringTool isn't dumping it for some reason.

**Comment by marcussacana** [comment]
This game works on the Vita3K? I can't do much without because I don't own an PSV

**Comment by badspott** [comment]
It should work on Vita3K per the Vita3K's compatibility list as well as the GitHub page (https://github.com/Vita3K/compatibility/issues/570). Though I didn't mess with Vita3K but rather on my Vita.

**Comment by marcussacana** [comment]
Update the PrototypeManager plugin and try again, but before close the issue check if the game runs normally on your real PSV after edit the script
seems to be fixed at least the dumping
![image](https://github.com/marcussacana/SacanaWrapper/assets/10576957/e76eb1d0-0599-43bb-bf4c-a63563865b7c)

**Comment by badspott** [comment]
I can confirm that it's fully working now. Thank you for fixing it! 
![2023-07-08-003446](https://github.com/marcussacana/SacanaWrapper/assets/21333472/30bf7c31-f00a-4fea-b6f2-cdd32bb90810)
