### ISSUE TITLE
Repacking to bgi (no extension files)?

### ISSUE THREAD

**Issue by Xylord666** [marcussacana/SacanaWrapper#26]
Is there a way to repack back into original files? For example, I can extract scripts from buriko general interpreter files by drag and drop onto StringTool.exe and I get a text dump, but is this only one way?

**Comment by marcussacana** [comment]
drag drop the txt after translate, but you need keep the original file and the translation in their original place and name to works.
if the tool fail to find the script due the missing extension, just manually set the command line with all file paths.
