### ISSUE TITLE
How to translate Alice soft Script using your tool

### ISSUE THREAD

**Issue by subaru471171** [marcussacana/SacanaWrapper#28]
I know that .ain file contains the script. but i am not getting to extract the script using your tool. Can you tell me the steps

**Comment by marcussacana** [comment]
.ain file is not directly supported, the ScanaWrapper plugin is just a filter for plain text of the script created by the AinDecompiler tool

**Comment by subaru471171** [comment]
But isnt Ain decompiler creates a main.jam file???

**Comment by marcussacana** [comment]
Uses the text export tool
