### ISSUE TITLE
Suggestion: add PJADV engine?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/SacanaWrapper#3]
tools for PJADV already exist, its [PrismArkTools](https://github.com/Doddler/PrismArkTools), even though this tools originally made for Prism Ark, i tried it and it works with other PJADV based engine games, of course i dont force you, but i think, this would be useful for your Sacana Wrapper (=

**Comment by marcussacana** [comment]
I Will ask permition to the creator of this tool, if he allow convert he tool, i can try.
Kek, plz, send a download link of the game to my email ddtank.marcus@gmail.com, I don't found the game.

**Comment by 0xh3LL0** [comment]
email sent

**Comment by 0xh3LL0** [comment]
also, you may take a look at this
http://www.doddlercon.com/main/?p=272

**Comment by marcussacana** [comment]
that game isn't the same engine, is from a lucifus....

**Comment by 0xh3LL0** [comment]
no...... ToT
the one working link for pajama soft game that i found is just that,
i guess it cant be helped then,
and sorry for spent your internet for nothing.
