### ISSUE TITLE
Plugin Manager Error

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/SacanaWrapper#4]
build success, but when i run it, its error...
<a href="https://imgur.com/UeTWaOS"><img src="https://i.imgur.com/UeTWaOS.png" title="source: imgur.com" /></a>
<a href="https://imgur.com/LqzxrB1"><img src="https://i.imgur.com/LqzxrB1.png" title="source: imgur.com" /></a>

**Comment by marcussacana** [comment]
strange, this is the url, who he connect, you have any firewall or tried  run in a offline computer?
```csharp
const string RepoPath = "https://raw.githubusercontent.com/marcussacana/SacanaWrapper/updater/Updater/";
...
const string UpdateFile = RepoPath + "Updater.ini";
//https://raw.githubusercontent.com/marcussacana/SacanaWrapper/updater/Updater/Updater.ini
```
Try open this link: https://raw.githubusercontent.com/marcussacana/SacanaWrapper/updater/Updater/Updater.ini

anyway, this is the part of the code who connect
https://github.com/marcussacana/SacanaWrapper/blob/master/PMan/Update.cs#L11

**Comment by 0xh3LL0** [comment]
so i need to online every time i want to use this?

**Comment by marcussacana** [comment]
Yep, I created this to don't need give the updated plugins to my translator every update, just run the "PMan" with -update and he will check update for all plugins installed...
And i think have no reason to use offline, since to remove a plugin is just delete it at the plugins directory.

**Comment by 0xh3LL0** [comment]
okay so i run it on internet enabled pc, and its run now...
thanks!
