### ISSUE TITLE
Question: does it support encrypted ks script?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/SacanaWrapper#5]
sorry if i much asking,
i just notice after update, that there is a new plugin called krkrfilter which (suppose to) support ks script, (not to confused with scn / psb which is supported)
i wont argue about the format since you mention that ks has dynamic format,

but here is my question:
does it support encrypted ks script? like the one used by [Cube](https://vndb.org/p735) / [Cuffs](https://vndb.org/p172) tittles? (i havent try it yet)
if not, will you add support in the future?

**Comment by marcussacana** [comment]
Send a sample

**Comment by 0xh3LL0** [comment]
dammit! i mistaken the game...
its not Cube / Cuffs, but AkabeiSoft
man... my Akabeisoft game already deleted so maybe i cant test it...
however quoting from [this guy from fuwanovel](https://forums.fuwanovel.net/topic/4887-data-extraction-thread/?do=findComment&comment=444683), 
he said the encryption is weak, so maybe you can take a look?
http://www.geocities.jp/keep_creating/DojinDOC/HowToDecrypt.html

**Comment by marcussacana** [comment]
I think isn't needed, but i has added support, just update it.

**Comment by marcussacana** [comment]
You can test encrypting any file with this tool: 
[krkr enc.rar](https://github.com/marcussacana/SacanaWrapper/files/1570465/krkr.enc.zip)
