### ISSUE TITLE
SoftPal plugin is not working

### ISSUE THREAD

**Issue by Arata12** [marcussacana/SacanaWrapper#8]
I installled the plugin and it didn't work, I replaced it with the one from [UnisonShiftManager
](https://github.com/marcussacana/UnisonShiftManager/releases/tag/1.0.8) and it worked.

**Comment by marcussacana** [comment]
He display any error?

**Comment by Arata12** [comment]
Uh, yeah, it's in spanish, though, btw, it only happens with certains text.dat

here:
EX: {0}System.Reflection.TargetInvocationException: Se produjo una excepcion en el destino de la invocacion. ---> System.ArgumentException: La matriz de destino no es lo suficientemente larga para copiar todos los elementos de la coleccion. Compruebe el indice de la matriz y la longitud.
   en System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   en System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   en UnisonShiftManager.DAT.Decrypt(Byte[] Script)
   en UnisonShiftManager.DAT.Import()
   --- Fin del seguimiento de la pila de la excepcion interna ---
   en DotNetVM.exec(Object[] Args, String Class, String Function, Assembly assembly) en C:\projects\sacanawrapper\SacanaWrapper\DNVM.cs:linea 94
   en DotNetVM.Call(String ClassName, String FunctionName, Object[] Arguments) en C:\projects\sacanawrapper\SacanaWrapper\DNVM.cs:linea 65
   en SacanaWrapper.Wrapper.TryImport(String Plugin, Byte[] Script) en C:\projects\sacanawrapper\SacanaWrapper\Wrapper.cs:linea 239
   en SacanaWrapper.Wrapper.Import(Byte[] Script, String Extension, Boolean PreventCorrupt, Boolean TryLastPluginFirst) en C:\projects\sacanawrapper\SacanaWrapper\Wrapper.cs:linea 97
   en StringTool.Program.Process(String[] args) en C:\projects\sacanawrapper\StringTool\Program.cs:linea 105

**Comment by marcussacana** [comment]
Looks like is just the plugin is outdated, i will fix tomorrow

**Comment by marcussacana** [comment]
Fixed
